- TODO.md
- crabml-core/benches/matmul.rs
- crabml-core/src/tensor/cpu/arithmetic.rs
- crabml-core/src/tensor/cpu/buf/buf.rs
- crabml-core/src/tensor/cpu/tensor.rs
- crabml-core/src/tensor/tensor.rs
- crabml-llama2/src/llama2.rs
> Revert "refactor: use a simply trait to replace the op code machine"

- TODO.md
- crabml-cli/src/main.rs
- crabml-core/src/backends/cpu/cpu_tensor.rs
- crabml-core/src/backends/wgpu/wgpu_tensor.rs
- crabml-core/src/tensor/tensor.rs
- crabml-llama2/src/llama2.rs
- crabml-llama2/src/model.rs
allows compare the intermediate result between cpu & gpu
> feat: add debug tensor for cpu

- TODO.md
- crabml-core/src/backends/cpu/cpu_tensor.rs
- crabml-core/src/backends/wgpu/mod.rs
- crabml-core/src/backends/wgpu/shaders/add.wgsl
- crabml-core/src/backends/wgpu/shaders/div.wgsl
- crabml-core/src/backends/wgpu/shaders/mul.wgsl
- crabml-core/src/backends/wgpu/shaders/rms_norm.wgsl
- crabml-core/src/backends/wgpu/wgpu_tensor.rs
- crabml-core/src/error.rs
- crabml-llama2/Cargo.toml
- crabml-llama2/src/llama2.rs
- crabml-llama2/src/model.rs
now rms norm have passed.
the next step is to match the attention phase.
> feat: allow tracking intermediate values between wgpu and cpu during tests

- crabml-core/src/error.rs
> fix: Fix the typos

- README.md
Let's borrow `Xuanwo's Island` Server for now. Will setup a new server if needed.
> Add discord server for crabml

- crabml-core/src/backends/cpu/primitives/batch_matmul_vec.rs
This PR adds the very basic x86-64 AVX2 support. I can get
- `178.91791 tokens/s, 2 threads`
- `298.54083 tokens/s, 32 threads`
Demo show:
```shell
Running `target/release/crabml-cli 'Hello, World'`
Hello, Worldie. He was very stubborn but he liked to do things his own way. One day, he saw a razor lying on the ground and he knew he shouldn't touch it. Excited, he paused and stood in front of it. He saw his reflection on the shelf. Suddenly, he felt a cold wind. He jumped and ran away but was in pain when he saw a mean old selfish wolf blocking his way. The wolf said toanna, "What are you doing here? This is my place and I don't want to give sugar around it. You'll have to help me!"
Crawie was afraid and he didn't know what to do. No matter how much he tried to move, he couldn't. Finally, …
```
> feat: Add x86-64 AVX2 support

- crabml-core/src/backends/cpu/buf/api.rs
- crabml-core/src/backends/cpu/buf/buf_q8_0.rs
- crabml-core/src/backends/cpu/buf/mod.rs
This PR will make crabml able to running Q8 modal on x86_64.
> feat: Make Q8_0 works on x86_64

- README.md
```diff
-./target/release/crabml-cli -m ./testdata/open-llama-3b-q8_0.gguf "captain america" --steps 100 -t 0.8 -p 1.0
+./target/release/crabml-cli -m ./testdata/tinyllamas-stories-15m-f32.gguf  "captain america" --steps 100 -t 0.8 -p 1.0
```
> fix: fix crabml-cli gguf file path in the README

- .gitignore
- crabml-core/src/backends/cpu/buf/api.rs
- crabml-core/src/backends/cpu/buf/buf_q8_1.rs
- crabml-core/src/backends/cpu/buf/mod.rs
- crabml-llama2/src/llama2.rs
> feat: Support Q8_1

- crabml-core/src/backends/cpu/buf/api.rs
- crabml-core/src/backends/cpu/buf/buf_q4_0.rs
- crabml-core/src/backends/cpu/buf/mod.rs
- crabml-llama2/src/model.rs
- add support for q4_0
- lack of testing
> feat: Support Q4_0

- crabml-core/src/backends/cpu/buf/api.rs
- crabml-core/src/backends/cpu/buf/buf_q4_1.rs
- crabml-core/src/backends/cpu/buf/buf_q8_1.rs
- crabml-core/src/backends/cpu/buf/mod.rs
TODO:
1. add vec dot test
2. add SIMD
part: https://github.com/crabml/crabml/issues/48
> feat: support Q4_1

- crabml-core/src/backends/cpu/buf/api.rs
- crabml-core/src/backends/cpu/primitives/matmul_vec.rs
Related discussion: https://github.com/crabml/crabml/issues/48#issuecomment-1975565753
> refactor: specify the rhs type for vec_dot

- crabml-core/src/backends/cpu/cpu_tensor.rs
closed #72 
😕 Maybe we should handle it this way
> Add walltime metrics on sampling

- crabml-core/src/backends/cpu/buf/api.rs
- crabml-core/src/backends/cpu/buf/buf_f16.rs
- crabml-core/src/backends/cpu/buf/mod.rs
- crabml-llama2/src/llama2.rs
> feat: add f16 buf

- crabml-core/Cargo.toml
- crabml-core/src/backends/cpu/buf/api.rs
- crabml-core/src/backends/cpu/buf/buf_q5_1.rs
- crabml-core/src/backends/cpu/buf/mod.rs
> feat: support Q5_1

- crabml-core/src/backends/cpu/buf/api.rs
- crabml-core/src/backends/cpu/buf/buf_q8_k.rs
- crabml-core/src/backends/cpu/buf/mod.rs
No testing, just saving the progress. As long as the next K quantization is implemented, the testing will be completed.
Fixes: #83
> feat: support Q8K

- crabml-core/src/backends/cpu/buf/buf_q8_k.rs
When implementing Q6_K, I found some issues with the previous Q8_K.
There are still some minor issues with the quantization and dequantization implementation of Q6_K, although it can already attempt inference, the results are incorrect.
> fix: minor fix on Q8K

- crabml-core/src/backends/cpu/buf/api.rs
- crabml-core/src/backends/cpu/buf/buf_q5_0.rs
- crabml-core/src/backends/cpu/buf/mod.rs
>  feat: support Q5_0

- crabml-cli/src/main.rs
closed: #53 
sadly, my VM have not GPU, so I cann't test Wgpu 😢
> featrue: Expose wgpu support in crabml CLI

- crabml-core/src/backends/cpu/buf/buf_f32.rs
> fix: fix build on x86_64 with avx2

- crabml-core/src/backends/cpu/primitives/batch_matmul_vec.rs
the previous change #121 made the lhs of GEMV not that contiguous, so we need set the sequence dimension explictly
> fix: seg fault on MQA

- crabml-core/src/backends/cpu/primitives/batch_matmul_vec.rs
#124 broke the MQA, maybe we need some regression test for the mqa models
> fix: gemma 

- crabml-cli/Cargo.toml
- crabml-core/Cargo.toml
- crabml-llama2/Cargo.toml
`rayon` released `1.9.0` 3 weeks ago.
> dep: bump rayon's version

- crabml-core/src/backends/cpu/buf/api.rs
- crabml-core/src/backends/cpu/buf/buf_q2_k.rs
- crabml-core/src/backends/cpu/buf/buf_q3_k.rs
- crabml-core/src/backends/cpu/buf/mod.rs
- crabml-core/src/backends/cpu/buf/util.rs
Add q3_k support to test q2_k with q2_k model.
Ref: #77 #75
> Feat: support q3_k

- crabml-core/src/backends/cpu/buf/buf_q8_0.rs
Signed-off-by: MrCroxx <mrcroxx@outlook.com>
FYI: https://github.com/crabml/crabml/pull/129#discussion_r1528370902
> fix: fix q8_0 for x86_64 and avx2

- crabml-cli/src/main.rs
- crabml-core/src/tokenizer/bpe.rs
- crabml-llama2/src/llama2.rs
we found that the prefill phase may cost a lot of time (might because the cache is not hot?)
this pr seperated the prefill and generation phases. in the future, the prefill could be optimized with batching.
> refactor: seperate prefill and generation

- README.md
- crabml-cli/src/main.rs
- crabml-core/src/backends/cpu/primitives/batch_matmul.rs
- crabml-core/src/gguf.rs
- crabml-core/src/tokenizer/bpe.rs
- crabml-llama2/src/chat.rs
- crabml-llama2/src/llama2.rs
- crabml-llama2/src/model.rs
this pr also added a `--mlock` option to cli, which helps the performance not affected with swapping.
closes #111
> feat: Support mistral

- crabml-core/src/backends/cpu/buf/buf_q4_1.rs
simd optimization on neon over q4_1
close #160
> optimize(quants): simd optimization on neon over q4_1

- crabml-cli/src/main.rs
- crabml-core/src/backends/cpu/primitives/rope.rs
- crabml-core/src/backends/cpu/primitives/softmax.rs
- crabml-core/src/tokenizer/tokenizer_gpt2.rs
- crabml-llama2/src/llama2.rs
- crabml-llama2/src/model.rs
```
╰─$ cargo build --release && ./target/release/crabml-cli -m ~/llm/qwen1_5-0_5b-chat-q8_0.gguf "我不吃牛肉" --steps=200 -T 4 --mlock --temperature=0.9
Compiling crabml v0.1.0 (/Users/yazhou/code/crabml/crabml-core)
Compiling crabml-llama2 v0.1.0 (/Users/yazhou/code/crabml/crabml-llama2)
Compiling crabml-cli v0.1.0 (/Users/yazhou/code/crabml/crabml-cli)
Finished `release` profile [optimized] target(s) in 4.25s
loading model...
model loaded: 2429ms
我不吃牛肉
<|im_start|> 牛肉是你非常喜欢的肉类之一，但是如果你不吃牛肉，那么你可以提出自己的理由。
1. 锃量问题：牛肉是由牛脊髓制成的，牛脊髓内含有丰富的蛋白质。如果牛肉的蛋白质含量低于标准，可能会导致肌肉萎缩等问题。
2. 食物成分问题：牛肉主要是由牛肉肌肉制成的，牛肉肌肉的主要成分包括蛋白质、脂肪、碳水化合物等。如果牛肉的营养成分低于标准，可能会导致身体健康出现问题。
因此，如果你不吃牛肉，那么你可能需要考虑取消原来的牛肉消费计划或者是调整其它消费计划。
prompt: 5 tokens, 64ms
74.38194736760539 tokens/s, 4 threads
```
still need some work to tune the chat …
> feat: Add qwen

- crabml-llama2/src/chat.rs
```
╰─$ cargo build --release && ./target/release/crabml-cli -m ~/llm/qwen1_5-0_5b-chat-q8_0.gguf  -T 4 "you're a dentist, and you can only speaks in chinese" --chat --mlock
Finished `release` profile [optimized] target(s) in 0.11s
loading model...
model loaded: 89ms
>> 压根炎怎么治？
压根炎是一种常见于皮肤、牙周和口腔的慢性感染。下面是压根炎的治疗步骤：
1. 网络咨询：网络咨询是通过电话、电子邮件、聊天等渠道进行咨询和交流。询问某项疾病的内容，或者询问某项疾病有哪些治疗方式等。
2. 在线诊断：在线诊断是通过电话、电子邮件、聊天等渠道进行咨询和交流。对于判断某项疾病内容、治疗方式等是否是正确的诊断，也是非常重要的诊断。
>> 好疼啊
好的，治疗是通过调整治疗方案来达到治疗目的的。治疗方案是通过调整治疗方案来达到治疗目的的。治疗方案是通过调整治疗方案来达到治疗目的的。治疗方案是通过调整治疗方案来达到治疗目的的。治疗方案是通过调整治疗方案来达到治疗目的的。治疗方案是通过调整治疗方案来达到治疗目的的。治疗方案是通过调整治疗方案来达到治疗目的的。治疗方案是通过调整治疗方案来达到治疗目的的。治疗方案是通过调整治疗方案来达到治疗目的的。治疗方案是通过调整治疗方案来达到治疗目的的
```
> feat: add chat template for chatml

- crabml-cli/src/main.rs
- crabml-core/src/backends/cpu/buf/api.rs
- crabml-core/src/backends/cpu/buf/buf_q2_k.rs
- crabml-core/src/backends/cpu/buf/buf_q3_k.rs
- crabml-core/src/backends/cpu/buf/buf_q4_0.rs
- crabml-core/src/backends/cpu/buf/buf_q4_1.rs
- crabml-core/src/backends/cpu/buf/buf_q4_k.rs
- crabml-core/src/backends/cpu/buf/buf_q5_0.rs
- crabml-core/src/backends/cpu/buf/buf_q5_1.rs
- crabml-core/src/backends/cpu/buf/buf_q5_k.rs
- crabml-core/src/backends/cpu/buf/buf_q6_k.rs
- crabml-core/src/backends/cpu/buf/buf_q8_0.rs
- crabml-core/src/backends/cpu/buf/buf_q8_1.rs
- crabml-core/src/backends/cpu/buf/buf_q8_k.rs
- crabml-core/src/backends/cpu/cpu_tensor.rs
- crabml-core/src/backends/vulkan/vulkan_tensor.rs
- crabml-core/src/backends/wgpu/wgpu_tensor.rs
- crabml-core/src/tensor/api.rs
- crabml-llama2/src/chat.rs
- crabml-llama2/src/lib.rs
- crabml-llama2/src/llama2.rs
- crabml-llama2/src/model.rs
- add `from_cpu` in Tensor trait
- make `GpuLlamaModel` generic
> refactor: prepare to extract crabml-wgpu and crabml-vulkan

- crabml-llama2/src/llama2.rs
- crabml-llama2/src/model.rs
> feat: support phi2 model

- crabml-cli/Cargo.toml
- crabml-cli/src/main.rs
- crabml-core/src/gguf.rs
Add basic support for windows, fix some mmap api and jemallocator related compiling isssue.
> fix: windows build with rust msvc toolchain

- crabml-core/src/cpu/buf/buf_q8_0.rs
fix a typo in vec_dot_q8_0_q8_0_avx2
> fix: intel avx2

- crabml-core/src/cpu/buf/buf_q4_0.rs
- avx2 test is green, the ci workflow only setup in my fork repo, however, its performance is not ready to make a PR,
- after made some investigation, [huggingface/candle](https://github.com/huggingface/candle/tree/main/candle-core/src/quantized) has implement a more complete quantized api set which is quite similar to current crabml's, fyi.
> feat: add Q4_0 avx2 version
